#ifndef __UDSDATATYPE_H__
#define __UDSDATATYPE_H__

#include <cstdint>

/* ------------------ BEGIN ------------------ */
/* ------ Addresses used in UDS frames ------- */

constexpr uint8_t DIAGNOSTIC_TOOL_INTERNAL_ADDR = 0xF4;     // reference to this system (in UDS frame)

/**
 * @brief ECU addresses used in UDS frames
 */
enum class EECUAddress : uint8_t
{
    ECU_MASTER_INTERNAL_ADDR = 0x10,
    ECU_DME_INTERNAL_ADDR = 0x12,
    ECU_KOMBI_INTERNAL_ADDR = 0x60,
    ECU_IHKA_INTERNAL_ADDR = 0x78
};

/* ------------------ END ------------------ */

/**
 * @brief UDS Service Identifiers used by client (diagnostic tool) based on ISO 14229
 */
enum class EUDSRequestSID : uint8_t
{
    DIAGNOSTIC_SESSION_CONTROL = 0x10,
    ECU_RESET = 0x11,

    CLEAR_DIAGNOSTIC_INFORMATION = 0x14,

    READ_DTC_INFORMATION = 0x19,

    READ_DATA_BY_IDENTIFIER = 0x22,
    READ_MEMORY_BY_ADDRESS = 0x23,
    READ_SCALING_DATA_BY_IDENTIFIER = 0x24,

    SECURITY_ACCESS = 0x27,
    COMMUNICATION_CONTROL = 0x28,
    AUTHENTICATION = 0x29,

    READ_DATA_BY_IDENTIFIER_PERIODIC = 0x2A,

    DYNAMICALLY_DEFINE_DATA_IDENTIFIER = 0x2C,

    WRITE_DATA_BY_IDENTIFIER = 0x2E,
    INPUT_OUTPUT_CONTROL_BY_IDENTIFIER = 0x2F,

    WRITE_MEMORY_BY_ADDRESS = 0x3D,
    TESTER_PRESENT = 0x3E,


    ROUTINE_CONTROL = 0x31,

    REQUEST_DOWNLOAD = 0x34,
    REQUEST_UPLOAD = 0x35,
    TRANSFER_DATA = 0x36,
    REQUEST_TRANSFER_EXIT = 0x37,
    REQUEST_FILE_TRANSFER = 0x38,

    ACCESS_TIMING_PARAMETERS = 0x83,
    SECURED_DATA_TRANSMISSION = 0x84,
    CONTROL_DTC_SETTINGS = 0x85,
    RESPONSE_ON_EVENT = 0x86,
    LINK_CONTROL = 0x87
};

/**
 * @brief UDS Service Identifiers used by server (ECU)
 */
enum class EUDSResponseSID : uint8_t
{
    DIAGNOSTIC_SESSION_CONTROL = 0x50,
    ECU_RESET = 0x51,

    CLEAR_DIAGNOSTIC_INFORMATION = 0x54,

    READ_DTC_INFORMATION = 0x59,

    READ_DATA_BY_IDENTIFIER = 0x62,
    READ_MEMORY_BY_ADDRESS = 0x63,
    READ_SCALING_DATA_BY_IDENTIFIER = 0x64,

    SECURITY_ACCESS = 0x67,
    COMMUNICATION_CONTROL = 0x68,
    AUTHENTICATION = 0x69,

    READ_DATA_BY_IDENTIFIER_PERIODIC = 0x6A,

    DYNAMICALLY_DEFINE_DATA_IDENTIFIER = 0x6C,

    WRITE_DATA_BY_IDENTIFIER = 0x6E,
    INPUT_OUTPUT_CONTROL_BY_IDENTIFIER = 0x6F,

    ROUTINE_CONTROL = 0x71,

    REQUEST_DOWNLOAD = 0x74,
    REQUEST_UPLOAD = 0x75,
    TRANSFER_DATA = 0x76,
    REQUEST_TRANSFER_EXIT = 0x77,
    REQUEST_FILE_TRANSFER = 0x78,

    WRITE_MEMORY_BY_ADDRESS = 0x7D,
    TESTER_PRESENT = 0x7E,
    NEGATIVE_RESPONSE = 0x7F,

    ACCESS_TIMING_PARAMETERS = 0xC3,
    SECURED_DATA_TRANSMISSION = 0xC4,
    CONTROL_DTC_SETTINGS = 0xC5,
    RESPONSE_ON_EVENT = 0xC6,
    LINK_CONTROL = 0xC7
};

/**
 * @brief UDS Data Identifiers
 */
enum class EUDSDID : uint16_t
{
    // ISO SAE Reserved
    ISO_SAE_RESERVED_START_0 = 0x0000,
    ISO_SAE_RESERVED_END_0 = 0x00FF,

    // Vehicle Manufacturer Specific
    VEHICLE_MANUFACTURER_SPECIFIC_START_0 = 0x0100,
    VEHICLE_MANUFACTURER_SPECIFIC_END_0 = 0xA5FF,

    // Reserved For Legislative Use
    RESERVED_LEGISLATIVE_START_0 = 0xA600,
    RESERVED_LEGISLATIVE_END_0 = 0xA7FF,

    // Additional Manufacturer-Specific Ranges
    VEHICLE_MANUFACTURER_SPECIFIC_START_1 = 0xA800,
    VEHICLE_MANUFACTURER_SPECIFIC_END_1 = 0xACFF,

    RESERVED_LEGISLATIVE_START_1 = 0xAD00,
    RESERVED_LEGISLATIVE_END_1 = 0xAFFF,

    VEHICLE_MANUFACTURER_SPECIFIC_START_2 = 0xB000,
    VEHICLE_MANUFACTURER_SPECIFIC_END_2 = 0xB1FF,

    RESERVED_LEGISLATIVE_START_2 = 0xB200,
    RESERVED_LEGISLATIVE_END_2 = 0xBFFF,

    VEHICLE_MANUFACTURER_SPECIFIC_START_3 = 0xC000,
    VEHICLE_MANUFACTURER_SPECIFIC_END_3   = 0xC2FF,

    RESERVED_LEGISLATIVE_START_3 = 0xC300,
    RESERVED_LEGISLATIVE_END_3 = 0xCEFF,

    VEHICLE_MANUFACTURER_SPECIFIC_START_4 = 0xCF00,

    KOMBI_RPM = 0xD106,
    KOMBI_DISTANCE = 0xD10D,
    KOMBI_FUEL = 0xD11F,
    KOMBI_SPEED = 0xD107,
    KOMBI_TEMP = 0xD112,

    IHKA_EVAPORATOR = 0xD95C,
    IHKA_TEMP_SELECTOR = 0xD977,
    IHKA_VENTILLATION_TEMP = 0xD957,

    VEHICLE_MANUFACTURER_SPECIFIC_END_4 = 0xEFFF,

    NETWORK_CONFIGURATION_TRACTOR_TRAILER_START = 0xF000,
    NETWORK_CONFIGURATION_TRACTOR_TRAILER_END = 0xF00F,

    VEHICLE_MANUFACTURER_SPECIFIC_START_5 = 0xF010,
    VEHICLE_MANUFACTURER_SPECIFIC_END_5 = 0xF0FF,

    IDENTIFICATION_OPTION_MANUFACTURER_SPECIFIC_START_0 = 0xF100,
    IDENTIFICATION_OPTION_MANUFACTURER_SPECIFIC_END_0 = 0xF17F,

    BOOT_SOFTWARE_IDENTIFICATION = 0xF180,
    APPLICATION_SOFTWARE_IDENTIFICATION = 0xF181,
    APPLICATION_DATA_IDENTIFICATION = 0xF182,
    BOOT_SOFTWARE_FINGERPRINT = 0xF183,
    APPLICATION_SOFTWARE_FINGERPRINT = 0xF184,
    APPLICATION_DATA_FINGERPRINT = 0xF185,
    ACTIVE_DIAGNOSTIC_SESSION = 0xF186,
    SPARE_PART_NUMBER = 0xF187,
    ECU_SOFTWARE_NUMBER = 0xF188,
    ECU_SOFTWARE_VERSION_NUMBER = 0xF189,
    SYSTEM_SUPPLIER_IDENTIFIER = 0xF18A,
    ECU_MANUFACTURING_DATE = 0xF18B,
    ECU_SERIAL_NUMBER = 0xF18C,
    SUPPORTED_FUNCTIONAL_UNITS = 0xF18D,
    KIT_ASSEMBLY_PART_NUMBER = 0xF18E,
    VIN = 0xF190,
    ECU_HARDWARE_NUMBER = 0xF191,
    SUPPLIER_HARDWARE_NUMBER = 0xF192,
    SUPPLIER_HARDWARE_VERSION = 0xF193,
    SUPPLIER_SOFTWARE_NUMBER = 0xF194,
    SUPPLIER_SOFTWARE_VERSION = 0xF195,
    EXHAUST_REGULATION_NUMBER = 0xF196,
    SYSTEM_NAME_OR_ENGINE_TYPE = 0xF197,
    REPAIR_SHOP_OR_TESTER_SERIAL = 0xF198,
    PROGRAMMING_DATE = 0xF199,
    CALIBRATION_SHOP_OR_EQUIPMENT = 0xF19A,
    CALIBRATION_DATE = 0xF19B,
    CALIBRATION_EQUIPMENT_SOFTWARE = 0xF19C,
    ECU_INSTALLATION_DATE = 0xF19D,
    ODX_FILE = 0xF19E,
    ENTITY_IDENTIFIER = 0xF19F,

    IDENTIFICATION_OPTION_MANUFACTURER_SPECIFIC_START_1 = 0xF1A0,
    IDENTIFICATION_OPTION_MANUFACTURER_SPECIFIC_END_1 = 0xF1EF,

    IDENTIFICATION_OPTION_SUPPLIER_SPECIFIC_START = 0xF1F0,
    IDENTIFICATION_OPTION_SUPPLIER_SPECIFIC_END = 0xF1FF,

    PERIODIC_DATA_IDENTIFIER_START = 0xF200,
    PERIODIC_DATA_IDENTIFIER_END = 0xF2FF,

    DYNAMICALLY_DEFINED_DATA_IDENTIFIER_START = 0xF300,
    DYNAMICALLY_DEFINED_DATA_IDENTIFIER_0 = 0xF300,
    DYNAMICALLY_DEFINED_DATA_IDENTIFIER_END = 0xF3FF,

    OBD_DATA_IDENTIFIER_START = 0xF400,
    OBD_DATA_IDENTIFIER_END = 0xF4FF,

    OBD_MONITOR_DATA_IDENTIFIER_START = 0xF600,
    OBD_MONITOR_DATA_IDENTIFIER_END = 0xF6FF,

    TACHOGRAPH_DATA_IDENTIFIER_START = 0xF900,
    TACHOGRAPH_DATA_IDENTIFIER_END = 0xF9FF,

    AIRBAG_DEPLOYMENT_IDENTIFIER_START = 0xFA00,
    AIRBAG_DEPLOYMENT_IDENTIFIER_END = 0xFA0F,

    SAFETY_SYSTEM_IDENTIFIER_START = 0xFA19,
    SAFETY_SYSTEM_IDENTIFIER_END = 0xFAFF,

    SYSTEM_SUPPLIER_SPECIFIC_START = 0xFD00,
    SYSTEM_SUPPLIER_SPECIFIC_END = 0xFEFF,

    UDS_VERSION = 0xFF00,

    ISO_SAE_RESERVED_START_1 = 0xFF01,
    ISO_SAE_RESERVED_END_1 = 0xFFFF
};

/**
 * @brief Identifiers used in BMW to request an assign of diagnostic param to Dynamically Defined Data Identifier
 */
enum class EDynamicDataIndentifierRequestCode : uint32_t
{
    ENGINE_SPEED = 0x48070102,
    COOLANT_TEMPERATURE = 0x43000101,
    ENGINE_OIL_TEMPERATURE = 0x44020102,
    BATTERY_VOLTAGE = 0x46090101,
    AMBIENT_TEMPERATURE = 0x42040101,
    AIR_MASS = 0x42080102,
    RAIL_PRESSURE = 0x481A0102,
    ACCELERATOR_PEDAL_POSITION = 0x4A290101
};

/**
 * @brief Sub-SIDs used in Dynamically Define Data Identifier service
 */
enum class DynamicallyAssignDataSubSID : uint8_t
{
    REQUEST_FIRST = 0x03,
    REQUEST_ASSIGN = 0x01
};

#endif /* __UDSDATATYPE_H__ */