DoIPDiagnoserCM7: Diagnose_ExtraVisualView Class Reference
Diagnose_ExtraVisualView Class Reference
View for Diagnose Extra Visual screen.
#include <Diagnose_ExtraVisualView.hpp>
Inherits Diagnose_ExtraVisualViewBase.
Public Member Functions
Diagnose_ExtraVisualView ()
Construct a new Diagnose Extra Visual View object.
virtual ~Diagnose_ExtraVisualView ()
Destroy the Diagnose Extra Visual View object.
virtual void setupScreen ()
Initialize the screen.
virtual void tearDownScreen ()
Tear down the screen.
void UpdateParameterValue (EEventType eventType, const UMessageData &data)
Update the diagnostic parameter value on screen.
void setTemperature (short int temperature)
Set the temperature on screen.
void setDate (uint8_t day, uint8_t month, unsigned int year)
Set the date on screen.
void setTime (uint8_t hour, uint8_t minute)
Set the time on screen.
void showPopup (uint8_t message[], size_t msgSize)
Show popup with message.
void ButtonUartClicked () override
Handle button UART clicked.
void graphOil_Clicked (AbstractDataGraph::GraphClickEvent value) override
Handle graph oil clicked.
void graphCoolant_Clicked (AbstractDataGraph::GraphClickEvent value) override
Handle graph coolant clicked.
void graphOil_Dragged (AbstractDataGraph::GraphDragEvent value) override
Handle graph oil dragged.
void graphCoolant_Dragged (AbstractDataGraph::GraphDragEvent value) override
Handle graph coolant dragged.
void setRequestCycleTime (uint16_t cycleMs)
Set request cycle time value on the screen.
Protected Member Functions
void updateInfoWidgetPosision_Oil ()
Update the position of value snippet on the oil graph.
void updateInfoWidgetPosision_Coolant ()
Update the position of value snippet on the coolant graph.
Detailed Description
View for Diagnose Extra Visual screen.
Definition at line 10 of file Diagnose_ExtraVisualView.hpp.
Member Function Documentation
graphCoolant_Clicked()
void Diagnose_ExtraVisualView::graphCoolant_Clicked (AbstractDataGraph::GraphClickEvent value) override
Handle graph coolant clicked.
Parameters
value graph click event
Definition at line 63 of file Diagnose_ExtraVisualView.cpp.
References updateInfoWidgetPosision_Coolant().
graphCoolant_Dragged()
void Diagnose_ExtraVisualView::graphCoolant_Dragged (AbstractDataGraph::GraphDragEvent value) override
Handle graph coolant dragged.
Parameters
value graph drag event
Definition at line 78 of file Diagnose_ExtraVisualView.cpp.
References updateInfoWidgetPosision_Coolant().
graphOil_Clicked()
void Diagnose_ExtraVisualView::graphOil_Clicked (AbstractDataGraph::GraphClickEvent value) override
Handle graph oil clicked.
Parameters
value graph click event
Definition at line 54 of file Diagnose_ExtraVisualView.cpp.
References updateInfoWidgetPosision_Oil().
graphOil_Dragged()
void Diagnose_ExtraVisualView::graphOil_Dragged (AbstractDataGraph::GraphDragEvent value) override
Handle graph oil dragged.
Parameters
value graph drag event
Definition at line 72 of file Diagnose_ExtraVisualView.cpp.
References updateInfoWidgetPosision_Oil().
setDate()
void Diagnose_ExtraVisualView::setDate (uint8_t day, uint8_t month, unsigned int year)
Set the date on screen.
Parameters
day day
month month
year year
Definition at line 124 of file Diagnose_ExtraVisualView.cpp.
setRequestCycleTime()
void Diagnose_ExtraVisualView::setRequestCycleTime (uint16_t cycleMs)
Set request cycle time value on the screen.
Parameters
cycleMs cycle duration is ms
Definition at line 168 of file Diagnose_ExtraVisualView.cpp.
setTemperature()
void Diagnose_ExtraVisualView::setTemperature (short int temperature)
Set the temperature on screen.
Parameters
temperature temperature value
Definition at line 118 of file Diagnose_ExtraVisualView.cpp.
setTime()
void Diagnose_ExtraVisualView::setTime (uint8_t hour, uint8_t minute)
Set the time on screen.
Parameters
hour hour
minute minute
Definition at line 130 of file Diagnose_ExtraVisualView.cpp.
showPopup()
void Diagnose_ExtraVisualView::showPopup (uint8_t message[], size_t msgSize)
Show popup with message.
Parameters
message message to show
msgSize message size
Definition at line 136 of file Diagnose_ExtraVisualView.cpp.
UpdateParameterValue()
void Diagnose_ExtraVisualView::UpdateParameterValue (EEventType eventType, const UMessageData & data)
Update the diagnostic parameter value on screen.
Parameters
eventType event type
data message data
Definition at line 19 of file Diagnose_ExtraVisualView.cpp.
The documentation for this class was generated from the following files:
C:/Users/jakub/Desktop/Praca_inz/stm32_workspace/stm32_doipdiagnoser/CM7/TouchGFX/gui/include/gui/diagnose_extravisual_screen/Diagnose_ExtraVisualView.hpp
C:/Users/jakub/Desktop/Praca_inz/stm32_workspace/stm32_doipdiagnoser/CM7/TouchGFX/gui/src/diagnose_extravisual_screen/Diagnose_ExtraVisualView.cpp