DoIPDiagnoserCM7: EventBus Class Reference
EventBus Class Reference
Wrapper class for freeRTOS message queues, that allows for processing events (messages in the queue) on demand from IN queue and sending messages through OUT queue.
#include <EventBus.h>
Public Types
typedef std::function< void(EEventType, UMessageData, EEventClient, EEventClient)> OnEventFunction
Callable object type that takes event type and message data as arguments. It is used for injecting a handle to process incoming events.
Public Member Functions
EventBus (QueueHandle_t queueSelf, EEventClient senderSelf)
Construct a new EventBus object.
bool send (EEventType event, UMessageData message, EEventClient eventReceiver)
Send event.
void receive (OnEventFunction onEventFunction)
Receive all incoming events.
Detailed Description
Wrapper class for freeRTOS message queues, that allows for processing events (messages in the queue) on demand from IN queue and sending messages through OUT queue.
Definition at line 22 of file EventBus.h.
Constructor & Destructor Documentation
EventBus()
EventBus::EventBus (QueueHandle_t queueSelf, EEventClient senderSelf)
Construct a new EventBus object.
Parameters
queueSelf self queue handle
senderSelf self sender
Definition at line 11 of file EventBus.cpp.
References EventBus().
Referenced by EventBus().
Member Function Documentation
receive()
void EventBus::receive (OnEventFunction onEventFunction)
Receive all incoming events.
Parameters
onEventFunction on event function (will be called for every incoming event)
Definition at line 31 of file EventBus.cpp.
Referenced by CalculatorTask::process(), IPCDaemonProxyTask::process(), and RTCTask::processIncomingEvents().
send()
bool EventBus::send (EEventType event, UMessageData message, EEventClient eventReceiver)
Send event.
Parameters
event event type
message message data
eventReceiver event receiver
Returns
true if success
Definition at line 16 of file EventBus.cpp.
Referenced by Model::sendEvent().
The documentation for this class was generated from the following files:
C:/Users/jakub/Desktop/Praca_inz/stm32_workspace/stm32_doipdiagnoser/Common/Inc/EventBus.h
Application/User/EventManagerCM7/src/EventBus.cpp